class BitString:
    def __init__(self) -> None: ...
    @property
    def bit_len(self) -> int: ...
    @property
    def remaining_bits(self) -> int: ...
    def seek(self, pos: int) -> None: ...
    def set_bit(self, pos: int, value: int) -> None: ...
    def get_bit(self, pos: int) -> bool: ...
    def append(self, bit: int) -> None: ...
    def append_value(self, value: int, bitcount: int) -> None: ...
    def read_bits(self, count: int) -> int: ...
    def read_chars(self, count: int) -> bytearray: ...
    def to_base64(self) -> str: ...
    def to_url_component(self) -> str: ...
    def to_text(self) -> str: ...
    @classmethod
    def from_base64(cls, input_text: str) -> "BitString": ...
    @classmethod
    def from_url_component(cls, input_text: str) -> "BitString": ...
    @classmethod
    def from_bit_text(cls, text: str) -> "BitString": ...
    @classmethod
    def from_bytes(cls, data: bytes) -> "BitString": ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
