import enum
from .BitString import BitString

class SpecialTokens(enum.IntEnum):
    LiteralByte = 0
    LiteralWord = 1
    EndOfStream = 2

class LZStringDecompressor:
    def __init__(self, bs: BitString) -> None: ...
    def decompress(self) -> bytearray: ...
    @classmethod
    def decompress_from_bytes(cls, data: bytes) -> bytearray: ...
    @classmethod
    def decompress_from_base64(cls, b64data: str) -> bytearray: ...
    @classmethod
    def decompress_from_url_component(
        cls, urlcomponent: str, escape: bool = ...
    ) -> bytearray: ...

class LZStringCompressor:
    def __init__(self, data: bytes) -> None: ...
    @property
    def token_bits(self) -> int: ...
    def compress(self) -> BitString: ...
    @classmethod
    def compress_to_bytes(cls, data: bytes) -> bytes: ...
    @classmethod
    def compress_to_base64(cls, data: bytes) -> str: ...
    @classmethod
    def compress_to_url_component(cls, data: bytes, escape: bool = ...) -> str: ...
